### ISSUE TITLE
support installation of nfs-common library for RHEL

### ISSUE THREAD

**Issue by jesusmah** [ibm-cloud-architecture/terraform-icp-vmware#20]
The `create-part.sh` script has a command `sudo apt -y install nfs-common`. That command and package doesn't exist in Red Hat Linux (RHEL) so the terraform fails and exits.  If we wish to confirm that NFS is installed and/or force the installation then the os variable needs to be checked and the RHEL command `sudo yum install nfs-utils` used instead. 

I believe this is addressed in the following commit of a pending PR: https://github.com/ibm-cloud-architecture/terraform-icp-vmware/pull/19/commits/f76762790c7c224a50e3b94bcab4a6644118aa94

**Comment by hassenius** [comment]
fixed with pr #19
